#!/bin/bash

is_alive_ping()
{
  ping -c 1 $1 > /dev/null
  [ $? -eq 0 ] && echo Хост с IP: $i поднят.
}

for i in 192.168.55.{2..253} 
do
is_alive_ping $i & disown
done


#!/bin/bash
#for ((i = 170; i < 190; i++))
#do
#ping 192.168.180.$i
#done

#нужно сделать исполняемым
